<?php

$servername = "172.20.3.98";
$username = "safety";
$password = "safety";
$dbname = "SafetyDL";

$DEPTNO = $_POST["DEPTNO"];
$LNAME = $_POST["LNAME"];
$FNAME = $_POST["FNAME"];
$MAILADDR1 = $_POST["MAILADDR1"];
$MAILADDR2 = $_POST["MAILADDR2"];
$COUNTYADDR = $_POST["COUNTYADDR"];
$BRTHCENTRY = $_POST["BRTHCENTRY"];
$BRTYEAR = $_POST["BRTYEAR"];
$BRTHMONTH = $_POST["BRTHMONTH"];
$BRTHDAY = $_POST["BRTHDAY"];
$DRIVERSEX = $_POST["DRIVERSEX"];
$CLIENTIDNO=$_POST['clientidno'];
$LISCENIDNO = $_POST["LISCENIDNO"];
$DRVRCLASS = $_POST["DRVRCLASS"];
$ENDORSMENT = $_POST["ENDORSEMNT"];
$RESTRICTNS = $_POST["RESTRICTNS"];
$EXPCENTURY = $_POST["EXPCENTRY"];
$EXPYEAR = $_POST["EXPYEAR"];
$EXPMONTH = $_POST["EXPMONTH"];
$EXPDAY = $_POST["EXPDAY"];
$CMPLCNTRY = $_POST["CMPLCNTRY"];
$CMPLYEAR = $_POST["CMPLYEAR"];
$CMPLMONTH = $_POST["CMPLMONTH"];
$CMPLDAY = $_POST["CMPLDAY"];
$NUMPOINTS = $_POST["NUMPOINTS"];
$DRVRVIOL1 = $_POST["DRVRVIOL1"];
$DRVRVIOL2 = $_POST["DRVRVIOL2"];
$DRVRVIOL3 = $_POST["DRVRVIOL3"];
$DRVRVIOL4 = $_POST["DRVRVIOL4"];
$DRVRVIOL5 = $_POST["DRVRVIOL5"];
$DRVRRMKS1 = $_POST["DRVRRMKS1"];
$DRVRRMKS2 = $_POST["DRVRRMKS2"];
$DRVRRMKS3 = $_POST["DRVRRMKS3"];

$conn = new mysqli($servername, $username, $password, $dbname);

$sql = "UPDATE Drivers SET DEPTNO='$DEPTNO', LNAME='$LNAME', FNAME='$FNAME', MAILADDR1='$MAILADDR1', MAILADDR2='$MAILADDR2', COUNTYADDR='$COUNTYADDR', BRTHCENTRY='$BRTHCENTRY', BRTYEAR='$BRTYEA', BRTHMONTH='$BRTHMONTH', BRTHDAY='$BRTHDAY', DRIVERSEX='$DRIVERSEX', LISCENIDNO='$LICENSIDNO', DRVRCLASS='$DRVRCLASS', ENDORSEMNT='$ENDORSEMNT', RESTRICTNS='$RESTRICTNS', EXPCENTRY='$EXPCENTRY', EXPYEAR='$EXPYEAR', EXPMONTH='$EXPMONTH', EXPDAY='$EXPDAY', CMPLCNTRY='$CMPLCNTRY', CMPLYEAR='$CMPLYEAR', CMPLMONTH='$CMPLMONTH', CMPLDAY='$CMPLDAY', NUMPOINTS='$NUMPOINTS', DRVRVIOL1='$DRVRVIOL1', DRVRVIOL2='$DRVRVIOL2', DRVRVIOL3='$DRVRVIOL3', DRVRVIOL4='$DRVRVIOL4', DRVRVIOL5='$DRVRVIOL5', DRVRRMKS1='$DRVRRMKS1', DRVRRMKS2='$DRVRRMKS2', DRVRRMKS3='$DRVRRMKS3' WHERE CLIENTIDNO=" . $CLIENTIDNO;
echo $sql . "<P>";
if ($conn->query($sql) === TRUE) {
    echo "New record created successfully";
    header("Location: test4.php");
} else {
    echo "Error: " . $sql . "<br>" . $conn->error;
}
$conn->close();

?>