<?php
$CLIENTIDNO=$_POST['CLIENTIDNO'];
echo $CLIENTIDNO;

$servername = "172.20.3.98";
$username = "safety";
$password = "safety";
$dbname = "SafetyDL";

$DEPTNO = $_POST["DEPTNO"];
$LNAME = $_POST["LNAME"];
$FNAME = $_POST["FNAME"];
$MAILADDR1 = $_POST["MAILADDR1"];
$MAILADDR2 = $_POST["MAILADDR2"];
$COUNTYADDR = $_POST["COUNTYADDR"];
$BRTHCENTRY = $_POST["BRTHCENTRY"];
$BRTYEAR = $_POST["BRTYEAR"];
$BRTHMONTH = $_POST["BRTHMONTH"];
$BRTHDAY = $_POST["BRTHDAY"];
$DRIVERSEX = $_POST["DRIVERSEX"];
$LISCENIDNO = $_POST["LISCENIDNO"];
$DRVRCLASS = $_POST["DRVRCLASS"];
$ENDORSEMNT = $_POST["ENDORSEMNT"];
$RESTRICTNS = $_POST["RESTRICTNS"];
$EXPCENTRY = $_POST["EXPCENTRY"];
$EXPYEAR = $_POST["EXPYEAR"];
$EXPMONTH = $_POST["EXPMONTH"];
$EXPDAY = $_POST["EXPDAY"];
$CMPLCNTRY = $_POST["CMPLCNTRY"];
$CMPLYEAR = $_POST["CMPLYEAR"];
$CMPLMONTH = $_POST["CMPLMONTH"];
$CMPLDAY = $_POST["CMPLDAY"];
$NUMPOINTS = $_POST["NUMPOINTS"];

$conn = new mysqli($servername, $username, $password, $dbname);

$sql = ("UPDATE Drivers SET DEPTNO=$DEPTNO, LNAME=$LNAME, FNAME=$FNAME, MAILADDR1=$MAILADDR1, MAILADDR2=$MAILADDR2, COUNTYADDR=$COUNTYADDR, BRTHCENTRY=$BRTHCENTRY, BRTYEAR=$BRTYEAR, BRTHMONTH=$BRTHMONTH, BRTHDAY=$BRTHDAY, DRIVERSEX=$DRIVERSEX, LISCENIDNO=$LISCENIDNO, DRVRCLASS=$DRVRCLASS, ENDORSEMNT=$ENDORSEMNT, RESTRICTNS=$RESTRICTNS, EXPCENTRY=$EXPCENTRY, EXPYEAR=$EXPYEAR, EXPMONTH=$EXPMONTH, EXPDAY=$EXPDAY, CMPLCNTRY=$CMPLCNTRY, CMPLYEAR=$CMPLYEAR, CMPLMONTH=$CMPLMONTH, CMPLDAY=$CMPLDAY, NUMPOINTS=$NUMPOINTS WHERE CLIENTIDNO= . $CLIENTIDNO");
echo $sql;
if ($conn->query($sql) === TRUE) {
    echo "New record created successfully";
    header("Location: test5.php");
} else {
    echo "Error: " . $sql . "<br>" . $conn->error;
}


?>